### ISSUE TITLE
Cannot build cperl-5.24.2

### ISSUE THREAD

**Issue by fperrad** [arsv/perl-cross#44]
New configuration variables are been introduced by `cperl-5.24.2`
```
/usr/bin/gcc -DPERL_CORE -DUSE_CROSS_COMPILE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fwrapv -fno-strict-aliasing -c -o miniperlmain.host.o miniperlmain.c
In file included from perl.h:31:0,
                 from miniperlmain.c:45:
xconfig.h:4026:3: error: invalid preprocessing directive #HAS_LLABS
 # HAS_LLABS  /**/
   ^
```
```
/home/dev/checkout/BR/build/cperl-cross/host/usr/bin/arm-linux-gnueabihf-gcc -c   -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -fwrapv -fno-strict-aliasing   -DVERSION=\"2.06c\" -DXS_VERSION=\"2.06c\" -fPIC -Wno-unused-function "-I../.."  -DLIBC="" DynaLoader.c
In file included from ../../perl.h:29:0,
                 from DynaLoader.xs:124:
../../config.h:4026:3: error: invalid preprocessing directive #HAS_LLABS
 # HAS_LLABS  /**/
```

Note: `Term::ReadKey` was bumped to version 2.37_01 (like `cperl-5.25.1`)

**Comment by arsv** [comment]
Well, fixed I think. Merged cperl-5.24.1 branch, most of the fixes were already there.

Right now it fails a single test for me, but it's not the one from #40. It's an unresolved reference in pod/perl5242cdelta.pod to YAML::XS::DisableBlessed. Looks like a documentation issue, the module itself does check the variable. Anyway, I think it's something that should better be dealt with upstream.

**Comment by fperrad** [comment]
Seems time for a new tag.
Just update dev variants (remove perl 5.25.5, 5.25.7 and replace them by 5.25.8)
